name: Staging deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./
          outPath: scraper.tar.gz
      - name: Get the output
        run: echo "The output was ${{ steps.compress.outputs.done }}"
      - name: Upload the artifact
        uses: actions/upload-artifact@v1
        with:
          name: scraper.tar.gz
          path: scraper.tar.gz
      - name: Download to the runner
        uses: actions/download-artifact@v2
        with:
          name: scraper.tar.gz
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Usage
        env:
          S3Key: "${{ steps.time.outputs.time }}-scraper.tar.gz"
        run: |
          echo $S3Key
      - name: AWS Deploy push
        uses: ItsKarma/aws-cli@v1.70.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        with:
          args: >-
            deploy push
            --application-name Scraper
            --description "This is a revision for the api-server"
            --ignore-hidden-files
            --s3-location s3://codedeploy-kaz/functioncode/${{env.S3Key}}
            --source scraper.tar.gz
      # - name: Upload to S3
      #   uses: zdurham/s3-upload-github-action@master
      #   with:
      #     args: --acl public-read
      #   env:
      #     FILE: scraper.tar.gz
      #     AWS_REGION: 'us-east-1'
      #     S3_BUCKET: ${{ secrets.AWS_BUCKET }}
      #     S3_KEY: ${{ env.S3Key }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: AWS Create Deploy
        uses: ItsKarma/aws-cli@v1.70.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        with:
          args: >-
            deploy create-deployment
            --application-name Scraper
            --deployment-config-name CodeDeployDefault.OneAtATime
            --deployment-group-name Sample
            --file-exists-behavior OVERWRITE
            --s3-location bucket=codedeploy-kaz,key=functioncode/${{ env.S3Key }},bundleType=tgz